"""add email unique constraint

Revision ID: 8f4963c50bc5
Revises: ba079b373774
Create Date: 2026-06-12 16:22:24.660589
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4963c50bc5'
down_revision: Union[str, None] = 'ba079b373774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False))
    op.drop_index(op.f('idx_provider_config_provider_name'), table_name='model_provider_configs')
    op.create_index(op.f('ix_model_provider_configs_provider_name'), 'model_provider_configs', ['provider_name'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_model_provider_configs_provider_name'), table_name='model_provider_configs')
    op.create_index(op.f('idx_provider_config_provider_name'), 'model_provider_configs', ['provider_name'], unique=False)
    op.drop_column('documents', 'is_public')
    # ### end Alembic commands ###
